name: onboard_client
description: The user-facing application for the Onboard Project, built with Flutter.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.2.0-Beta
environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  onboard_sdk:
     git:
        url: "git@github.com:onboard-project/sdk.git"
  flutter_map: ^8.2.1
  latlong2: ^0.9.1
  flex_color_scheme: ^8.2.0
  shared_preferences: ^2.5.3
  go_router: ^16.1.0
  bitsdojo_window: ^0.1.6
  fluentui_system_icons: ^1.1.273
  geolocator: ^14.0.2
  flutter_map_marker_cluster:
   git:
      url: https://github.com/matteomrz/flutter_map_marker_cluster
      ref: master
  skeletonizer: ^2.1.0+1
  flutter_map_location_marker: ^10.1.0
  provider: ^6.1.5+1
  material_symbols_icons: ^4.2873.0
  markdown_widget: ^2.3.2+8
  hive_ce: ^2.14.0
  hive_ce_flutter: ^2.3.2
  uuid: ^4.5.1
 
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  fonts:
     - family: DINNext
       fonts:
         - asset: lib/assets/fonts/DINNextW1G-Black.otf
           weight: 900
         - asset: lib/assets/fonts/DINNextW1G-BlackItalic.otf
           weight: 900
           style: italic
         - asset: lib/assets/fonts/DINNextW1G-Bold.otf
           weight: 700
         - asset: lib/assets/fonts/DINNextW1G-BoldItalic.otf
           style: italic
           weight: 700
         -  asset: lib/assets/fonts/DINNextW1G-Heavy.otf
            weight: 800
         -  asset: lib/assets/fonts/DINNextW1G-HeavyItalic.otf
            style: italic
            weight: 800
         -  asset: lib/assets/fonts/DINNextW1G-Italic.otf
            style: italic
            weight: 400
         -  asset: lib/assets/fonts/DINNextW1G-Light.otf
            weight: 300
         -  asset: lib/assets/fonts/DINNextW1G-LightItalic.otf
            style: italic
            weight: 300
         -  asset: lib/assets/fonts/DINNextW1G-Medium.otf
            weight: 500
         -  asset: lib/assets/fonts/DINNextW1G-MediumItalic.otf
            style: italic
            weight: 500
         -  asset: lib/assets/fonts/DINNextW1G-Regular.otf
            weight: 400
         -  asset: lib/assets/fonts/DINNextW1G-UltraLight.otf
            weight: 100
         -  asset: lib/assets/fonts/DINNextW1G-UltraLightIt.otf
            style: italic
            weight: 100

